### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by mobdim** [jfahrenkrug/StoryboardLint#10]
I did everything according to instructions. But on an empty project (Storyboard present) I got:

```
/Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:169:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:169:in `block (2 levels) in scan_files'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:167:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:167:in `each_with_index'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:167:in `block in scan_files'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:166:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:166:in `scan_files'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:153:in `class_names'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:294:in `block in check_custom_classes'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:293:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:293:in `check_custom_classes'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:276:in `lint'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/lib/storyboardlint.rb:374:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/storyboardlint-0.2.2/bin/storyboardlint:5:in `<top (required)>'
    from /usr/bin/storyboardlint:23:in `load'
    from /usr/bin/storyboardlint:23:in `<main>'
Command /bin/sh failed with exit code 1

```

Xcode 5.1.1

**Comment by phatblat** [comment]
Inserting the encode call fixed this issue for me as well. I'll send up a pull request.
